config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|fr/ do
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new"
      get "/sign_out" => "devise/sessions#destroy"
      get "/sign_up" => "devise/registrations#new"
    end

    get '/blog', to: 'pages#blog'
    get '/blog-single', to: 'pages#blog'
    get '/bridesmaids', to: 'pages#bridesmaids'
    get '/contact', to: 'pages#contact'
    get '/faq', to: 'pages#faq'
    get '/page', to: 'pages#page'
    get '/photos', to: 'pages#photos'
    get '/registry', to: 'pages#registry'
    get '/vendors', to: 'pages#vendors'
    get '/venue', to: 'pages#venue'

    get '/rsvp', to: 'rsvp#rsvp'
    match '/code', to: 'rsvp#code', via: [:get, :post]
    resource :rsvp, controller: 'rsvp'

    #get '/:locale' => 'pages#index'
    root 'pages#index'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  self.table_name= 'rsvp'

  belongs_to :user
  has_many :rsvp_guests, inverse_of: :rsvp, dependent: :destroy
  accepts_nested_attributes_for :rsvp_guests, allow_destroy: true, reject_if: proc { |a| a['name'].blank? }


end

app/models/rsvp_guest.rb
class RsvpGuest < ApplicationRecord
  belongs_to :rsvp

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_one :user_config, dependent: :destroy
  has_one :rsvp, dependent: :destroy

  before_create :build_default_user_config

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

  def build_default_user_config
    build_user_config(invitation_type: 'undeclared')
    true
  end
end

app/models/user_config.rb
class UserConfig < ApplicationRecord
  belongs_to :user

  enum invitation_type: [:undeclared, :solo, :couple, :family]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :store_user_location!, if: :storable_location?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

private
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      flash[:notice] = 'Please log in first'
      redirect_to sign_in_path
    end
  end

  def set_locale
    I18n.locale = params[:locale] || :en
  end

  def default_url_options
    { locale: I18n.locale }
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:rsvp, :code]

  PHOTOS_FOLDER = %w(engagement_shoot venue)

  def photos
    @photos = {}

    PHOTOS_FOLDER.each do |folder|
      files = Dir.glob("app/assets/images/#{folder}/*.*").map { |file| File.basename file, ".*" }
      @photos[folder] = files.sort
    end
  end

end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  before_action :authenticate_user!

  SOLO_CODE = Rails.application.secrets.solo_code
  COUPLE_CODE = Rails.application.secrets.couple_code
  FAMILY_CODE = Rails.application.secrets.family_code

  def rsvp
    if current_user.user_config.undeclared?
      redirect_to code_path
    else
      @rsvp = current_user.rsvp || Rsvp.new
      @rsvp.rsvp_guests.build unless @rsvp.rsvp_guests.any?
    end
  end

  def create
    @rsvp = current_user.build_rsvp(permitted_params)

    if @rsvp.save
      flash[:success] = t('rsvp.save_success')
      redirect_to :back
    else
      render :rsvp
    end
  end

  def update
    @rsvp = current_user.rsvp
    if @rsvp.update(permitted_params)
      flash[:success] = t('rsvp.save_success')
      redirect_to :back
    else
      render :rsvp
    end
  end


  def code
    redirect_to rsvp_path unless current_user.user_config.undeclared?

    if params[:code]
      case params[:code].upcase
        when SOLO_CODE
          current_user.user_config.solo!
        when COUPLE_CODE
          current_user.user_config.couple!
        when FAMILY_CODE
          current_user.user_config.family!
        else
          flash[:alert] = 'Invalid code'
      end
      redirect_to rsvp_path unless flash[:alert]
    end
  end

private

  def permitted_params
    params.require(:rsvp).permit(:event, :menu_selection, :note, rsvp_guests_attributes: [:id, :name, :email, :meal_selection, :note, :_destroy])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    if request.env["omniauth.auth"].info.email.blank?
      flash[:alert] = 'You need to share your Facebook email to continue.'
      return redirect_to sign_in_path
      # return redirect_to user_facebook_omniauth_authorize_path(auth_type: 'rerequest', scope: 'email')
    end

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to sign_in_url
    end
  end

  def failure
    flash[:alert] = "Error while trying to log in with Facebook. Try again."
    redirect_to sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'selected' : ''

    link_to link_text, link_path, :class => class_name
  end
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/views/layouts/_footer.erb
<div class="home_bottom">
  <div class="full_width_centered">
    <div class="left13">
      <div class="bottom_icon"><%= image_tag "template/icon_vacation.png" %></div>
      <h2><%= t('hotel.title') %></h2>
      <span class="subtitle"><%= t('hotel.subtitle') %></span>
      <p><%= t('hotel.content') %></p>
      <br>
      <!--a href="/page" class="post_read_more"><%= t('read_more') %></a-->
    </div>
    <div class="left13">
      <div class="bottom_icon"><%= image_tag "template/icon_location.png" %></div>
      <h2><%= t('location.title') %></h2>
      <span class="subtitle"><%= t('location.subtitle') %></span>
      <p><%= t('location.content') %></p>
      <%= link_to t('read_more'), venue_path, class: 'post_read_more' %>
    </div>
    <div class="left13_last">
      <div class="bottom_icon"><%= image_tag "template/icon_gifts.png" %></div>
      <h2><%= t('gift_registry.title') %></h2>
      <span class="subtitle"><%= t('gift_registry.subtitle') %></span>
      <p><%= t('gift_registry.content') %></p>
      <br><br>
      <%= link_to t('menu.registry'), registry_path, class: 'post_read_more' %>
    </div>

    <div class="clear"></div>
  </div>
</div>

<div class="footer">
  <div class="full_width_centered">
    <div class="footer_sign">
      <span class="swirl_left_transparent"><span class="swirl_right_transparent"><%= image_tag "template/birds_icon.png" %></span></span>
    </div>
    <div class="footer_names">SOPHIE &amp; GABRIEL</div>
    <!--div class="footer_socials">
      <ul>
        <li><a href="#"><%= image_tag "template/social/twitter.png" %></a></li>
        <li><a href="#"><%= image_tag "template/social/facebook.png" %></a></li>
        <li><a href="#"><%= image_tag "template/social/pinterest.png" %></a></li>
        <li><a href="#"><%= image_tag "template/social/vimeo.png" %></a></li>
        <li><a href="#"><%= image_tag "template/social/google.png" %></a></li>
        <li><a href="#"><%= image_tag "template/social/youtube.png" %></a></li>
      </ul>
    </div-->
    <nav class="footer_menu">
      <ul>
        <li><%= nav_link t('menu.home'), root_path %></li>
        <li><%= nav_link t('menu.wedding'), venue_path %></li>
        <li><%= nav_link t('menu.photos'), photos_path %></li>
        <li><%= nav_link t('menu.rsvp'), rsvp_path %></li>
        <li><%= nav_link t('menu.registry'), registry_path %></li>
        <li><%= nav_link t('menu.faq'), faq_path %></li>
        <!--li><%= nav_link t('menu.contact'), contact_path %></li-->
        <li>
          <a onClick="jQuery('html, body').animate( { scrollTop: 0 }, 'slow' );" href="javascript:void(0);" class="gotop"><%= t('menu.top') %></a>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_menu.erb
<a class="show_menu" href="#"><%= image_tag "template/mobile_menu_open.png" %></a>
<a class="hide_menu" href="#"><%= image_tag "template/mobile_menu_close.png" %></a>

<nav class="menu">
  <ul id="main_menu">
    <li><%= nav_link t('menu.home'), root_path %></li>
    <li><%= nav_link t('menu.wedding'), venue_path %>
      <ul>
        <li><%= nav_link t('menu.venue'), venue_path %></li>
        <li><%= nav_link t('menu.vendors'), vendors_path %></li>
      </ul>
    </li>
    <li><%= nav_link t('menu.photos'), photos_path %></li>
    <li><%= nav_link t('menu.rsvp'), rsvp_path %></li>
    <li><%= nav_link t('menu.registry'), registry_path %></li>
    <li><%= nav_link t('menu.faq'), faq_path %></li>
    <!--li><%= nav_link t('menu.contact'), contact_path %></li-->
    <% if user_signed_in? %>
      <li><%= nav_link t('menu.logout'), sign_out_path %></li>
    <% else %>
     <li><%= nav_link t('menu.signin'), sign_in_path %></li>
    <% end %>

    <% if I18n.locale == :fr %>
      <li><%= nav_link t('menu.english'), locale: 'en' %></li>
    <% else %>
      <li><%= nav_link t('menu.francais'), locale: 'fr' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gabriel and Sophie's Wedding</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1" />
    <meta name="author" content="Gabriel Gagnon" />
    <meta name="keywords" content="wedding, marriage, gabriel, sophie, 2018, quebec" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= favicon_link_tag 'favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
    <%= favicon_link_tag 'favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
    <link href='https://fonts.googleapis.com/css?family=Clicker+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/blog.html.erb
<div id="main_container">

    <%= render 'layouts/menu' %>

  <div class="blog_header_photo">
    <div class="page_header_trans">
      <div class="page_header_title">

      </div>
    </div>
  </div>

    <div class="blog_content">
     <div class="full_width_centered">
       <h2>OUR BLOG</h2>

       <div class="latest_posts">
         <h2><%= t('blog.title') %></h2>
         <div class="left13">
           <div class="latest_post">
             <div class="post_info">
               <span class="post_date"><%= t('blog.proposal.date') %></span>
               <h3><a href="/blog-single"><%= t('blog.proposal.title') %></a></h3>
               <a href="/blog-single" class="post_read_more"><%= t('read_more') %></a>
             </div>
             <%= image_tag "template/post_thumb1.jpg" %>
           </div>
         </div>
         <div class="left13">
           <div class="latest_post">
             <div class="post_info">
               <span class="post_date"><%= t('blog.wedding_organisation.date') %></span>
               <h3><a href="/blog-single"><%= t('blog.wedding_organisation.title') %></a></h3>
               <a href="/blog-single" class="post_read_more"><%= t('read_more') %></a>
             </div>
             <%= image_tag "template/post_thumb2.jpg" %>
           </div>
         </div>
         <div class="left13_last">
           <div class="latest_post">
             <div class="post_info">
               <span class="post_date"><%= t('blog.honeymoon.date') %></span>
               <h3><a href="/blog-single"><%= t('blog.honeymoon.title') %></a></h3>
               <a href="/blog-single" class="post_read_more"><%= t('read_more') %></a>
             </div>
             <%= image_tag "template/post_thumb3.jpg" %>
           </div>
         </div>
         <!--a href="/blog" class="view_all"><%= t('blog.more') %></a-->
         <div class="clear"></div>
       </div>
        </div>  <!--end of full width-->
      </div> <!--end of about content-->   

   <%= render 'layouts/footer' %>

</div>
<script type="text/javascript">
var main_menu=new main_menu.dd("main_menu");
main_menu.init("main_menu","menuhover");
</script>

app/views/pages/bridesmaids.html.erb
<div id="main_container">

  <%= render 'layouts/menu' %>

    <div class="page_header_photo general_header">
      <div class="page_header_trans">
               <div class="page_header_title">
               <h1>OUR BRIDESMAIDS AND GROOMSMEN'S</h1>
<p>Love is friendship that has caught fire. It is quiet understanding, sharing and forgiving. <br />
It is loyalty through good and bad times. It settles for less than perfection<br /> and makes allowances for human weaknesses.</p>
               </div>
       </div>
   </div>

    <div class="page_content">
     
     
     <div class="full_width_carousel">
        <div class="bridesmaids_listing">
            <div class="left14"><div class="bestman"><span>BEST MAN</span><%= image_tag "template/bestman.png" %></div><%= image_tag "template/image_14.jpg" %><h3>MIKE STEPHANSON</h3></div>
            <div class="left14"><div class="bestman"><span>MAID OF HONOR</span><%= image_tag "template/maidofhonor.png" %></div><%= image_tag "template/image_14_3.jpg" %><h3>LINDSEY REMY</h3></div>
            <div class="left14"><%= image_tag "template/image_14_2.jpg" %><h3>ELIZABETH LYN</h3></div>
            <div class="left14_last"><%= image_tag "template/image_14_6.jpg" %><h3>STEVE KAY</h3></div>
            <div class="left14"><%= image_tag "template/image_14_5.jpg" %><h3>JOHN DOE</h3></div>
            <div class="left14"><%= image_tag "template/image_14_3.jpg" %><h3>MAYA ELIOT</h3></div>
            <div class="left14"><%= image_tag "template/image_14_7.jpg" %><h3>JOHANNA PASCAL</h3></div>
            <div class="left14_last"><%= image_tag "template/image_14_8.jpg" %><h3>JOHN DOE</h3></div>
        </div>  

   <div class="clear"></div>		
     </div>

    
       

      </div> <!--end of about content-->   
  
  
  <div class="home_bottom">
      <div class="full_width_centered">
            <div class="left13"> 
            <div class="bottom_icon"><%= image_tag "template/icon_music.png" %></div>
            <h2>BACHELOR PARTY</h2>
            <span class="subtitle">BRING YOUR DANCING SHOES</span>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse <strong>cillum dolore</strong> eu fugiat nulla pariat ur si nt oc caecat non proident, sunt in culpa <a href="#">qui officia</a> deserunt mollit anim id est laborum sed quia non numquam eius modi.</p>
            <a href="/page" class="post_read_more">READ MORE</a>
            </div>
            <div class="left13">
            <div class="bottom_icon"><%= image_tag "template/icon_location.png" %></div>
            <h2>WEDDING LOCATION</h2>
            <span class="subtitle">VENICE, ITALY - HOTEL ADAM</span>
            <p>Nemo enim ipsam voluptatem <strong>quia voluptas</strong> sit aspernatur aut odit aut fugit, sed quia consequuntur <a href="#">magni</a> dolores eos qui ratione voluptatem sequi nesciunt. Neque quisquam est, qui dolorem ipsum</p>
            <a href="/page" class="post_read_more">READ MORE</a>
            </div>
            <div class="left13_last">
            <div class="bottom_icon"><%= image_tag "template/icon_gifts.png" %></div>
            <h2>GIFT REGISTRY</h2>
            <span class="subtitle">GIVEN FREELY AND OUT OF PURE LOVE</span>
            <p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit <a href="#">esse quam nihil</a> aspernatur aut odit aut fugit molestiae consequatur, vel illum <strong>qui dolorem</strong> eum fugiat quo voluptas nulla pariatur aspernatur.</p>
            <a href="/page" class="post_read_more">READ MORE</a>
            </div>
            
            <div class="clear"></div>
      </div>
  </div>
   
   <%= render 'layouts/footer' %>

</div>
<script type="text/javascript">
var $ = jQuery.noConflict();
  $(window).load(function() {
   "use strict"; 
   var $bestman = $('.bestman span').hide();
   $bestman.show().arctext({radius: 80});
 	

  });
</script>
<script type="text/javascript">
var main_menu=new main_menu.dd("main_menu");
main_menu.init("main_menu","menuhover");
</script>

app/views/pages/faq.html.erb
<div id="main_container">

  <%= render 'layouts/menu' %>

  <div class="blog_header_photo">
    <div class="page_header_trans">
      <div class="page_header_title">

      </div>
    </div>
  </div>


  <div class="page_content">
    <div class="full_width_centered">
      <h2><%= t('faq.name') %></h2>
      <div class="left_full">
        <h6><%= t('faq.question.q1') %></h6>
        <p><%= t('faq.answer.a1_html') %></p>
        <h6><%= t('faq.question.q2') %></h6>
        <p><%= t('faq.answer.a2') %></p>
        <h6><%= t('faq.question.q3') %></h6>
        <p><%= t('faq.answer.a3') %></p>
        <h6><%= t('faq.question.q4') %></h6>
        <p><%= t('faq.answer.a4') %></p>
        <h6><%= t('faq.question.q5') %></h6>
        <p><%= t('faq.answer.a5') %></p>
        <h6><%= t('faq.question.q6') %></h6>
        <p><%= t('faq.answer.a6_html') %></p>
        <h6><%= t('faq.question.q7') %></h6>
        <p><%= t('faq.answer.a7') %></p>
        <h6><%= t('faq.question.q8') %></h6>
        <p><%= t('faq.answer.a8') %></p>
        <h6><%= t('faq.question.q9') %></h6>
        <p><%= t('faq.answer.a9_html', href: link_to(t('faq.answer.a9_href'), registry_path)) %></p>
        <h6><%= t('faq.question.q10') %></h6>
        <p><%= t('faq.answer.a10') %></p>
        <h6><%= t('faq.question.q11') %></h6>
        <p><%= t('faq.answer.a11') %></p>
        <h6><%= t('faq.question.q12') %></h6>
        <p><%= t('faq.answer.a12') %></p>

      </div>

      <div class="clear"></div>
    </div>  <!--end of full width-->
  </div> <!--end of about content-->

  <%= render 'layouts/footer' %>

</div>
<script type="text/javascript">
    var main_menu = new main_menu.dd("main_menu");
    main_menu.init("main_menu", "menuhover");
</script>

app/views/pages/index.html.erb
<div id="main_container">

  <%= render 'layouts/menu' %>

  <div class="title_container">

    <div class="title_front"><%= t('title.front') %></div>
    <div class="love_birds"><%= image_tag "template/birds_icon.png" %></div>
    <div class="title">Sophie <span>&amp;</span> Gabriel</div>
    <div class="title_date"><span class="swirl_left"><span class="swirl_right"><%= t('title.date') %></span></span></div>
    <div class="title_under"><%= t('title.under') %></div>

  </div>

  <div class="slider_container">
    <!--div class="slider_trans_black"></div-->
    <div id="random">
      <div style="background-image: url(<%= image_path 'engagement_shoot/18-201_SophieGabriel_100071' %>) ;"></div>
      <div style="background-image: url(<%= image_path 'engagement_shoot/18-201_SophieGabriel_100039' %>) ;"></div>
      <div style="background-image: url(<%= image_path 'engagement_shoot/18-201_SophieGabriel_100004' %>) ;"></div>
      <div style="background-image: url(<%= image_path 'engagement_shoot/18-201_SophieGabriel_100023' %>) ;"></div>
    </div>
  </div>
  <div class="countdown_container">
    <h2 class="centered_title">#GABGAGNESOF</h2>
    <div id="defaultCountdown"></div>
    <div class="rsvp_button">
      <span class="swirl_left_small"><span class="swirl_right_small"><%= link_to t('countdown.rsvp'), rsvp_path %></span></span></div>
  </div>

  <div class="about_content">
    <div class="about_topsign">&amp;</div>
    <div class="full_width_centered">


      <div class="left12_first">
        <span class="names_titles"><%= t('index.bride.title') %></span>
        <h2>SOPHIE ZHU</h2>
        <div class="about_pic_container">
          <span class="about_picframe"></span>
          <div class="about_pic"><%= image_tag "headshots/headshot_sophie.jpg" %></div>
        </div>
        <a href="https://www.facebook.com/sophie.zhu" class="thumb_read_more"><%= t('index.bride.subtitle') %></a>
        <p><%= t('index.bride.content') %></p>

      </div>
      <div class="left12_last">
        <span class="names_titles"><%= t('index.groom.title') %></span>
        <h2>GABRIEL GAGNON</h2>
        <div class="about_pic_container">
          <span class="about_picframe"></span>
          <div class="about_pic"><%= image_tag "headshots/headshot_gabriel.jpg" %></div>
        </div>
        <a href="https://www.facebook.com/gabriel.gagnon.501" class="thumb_read_more"><%= t('index.groom.subtitle') %></a>
        <p><%= t('index.groom.content') %></p>
      </div>

      <div class="clear"></div>
    </div>  <!--end of full width-->
  </div> <!--end of about content-->

  <div class="carousel_container">
    <div class="carousel_container_image">
      <div class="full_width_carousel">
        <h2><%= t('index.groomlist.title') %></h2>
        <span class="carousel_titles"><%= t('index.groomlist.subtitle_html') %></span>
        <div id="weddingcarousel" class="owl-carousel">
          <div class="left14">
            <div class="bestman"><span><%= t('index.groomlist.bestman') %></span><%= image_tag "template/bestman.png" %>
            </div><%= image_tag "headshots/headshot_philippe.jpg" %><h3>PHILIPPE BOIVIN</h3></div>
          <div class="left14">
            <div class="bestman"><span><%= t('index.groomlist.bestman') %></span><%= image_tag "template/bestman.png" %>
            </div><%= image_tag "headshots/headshot_laurent.jpg" %><h3>LAURENT DANG</h3></div>
          <div class="left14">
            <div class="bestman"><span><%= t('index.groomlist.maidofhonor') %></span><%= image_tag "template/maidofhonor.png" %>
            </div><%= image_tag "headshots/headshot_lucie.jpg" %><h3>LUCY LUO</h3></div>
          <div class="left14_last"><%= image_tag "headshots/headshot_ella.jpg" %><h3>ELLA BENZAQUEN</h3></div>
          <div class="left14"><%= image_tag "headshots/headshot_rachelle.jpg" %><h3>RACHELLE DE MUY</h3></div>
          <div class="left14"><%= image_tag "headshots/headshot_pl.jpg" %><h3>PIERRE-LUC FAUCHER</h3></div>
          <div class="left14"><%= image_tag "headshots/headshot_as.jpg" %><h3>ANNE-SOPHIE GAGNON</h3></div>
          <div class="left14_last"><%= image_tag "headshots/headshot_ka.jpg" %><h3>KARL-ANDRÉ GAGNON</h3></div>
          <div class="left14"><%= image_tag "headshots/headshot_gabrielle.jpeg" %><h3>GABRIELLE MAHEUX-LECLERC</h3></div>
          <div class="left14"><%= image_tag "headshots/headshot_karen.jpg" %><h3>KAREN TAM</h3></div>
          <div class="left14_last"><%= image_tag "headshots/headshot_victor.jpg" %><h3>VICTOR TSANG-HI</h3></div>
        </div>
        <!--div class="view_all_carousel"><%= link_to t('index.groomlist.more'), bridesmaids_path %></div-->
      </div>
    </div>
  </div>


  <%= render 'layouts/footer' %>

</div>
<script>
    $(document).ready(function () {
        "use strict";
        $("#random").skippr({
            navType: 'bubble',
            transition: 'fade',
            autoPlay: true,
            autoPlayDuration: 4000,
            speed: 1000,
            arrows: true
        });
        $("#weddingcarousel").owlCarousel({
            items: 4,
            itemsScaleUp: true,
            lazyLoad: true,
            navigationText: ["prev", "next"],
        })
    });
</script>
<!-- DropDownMenu -->
<script type="text/javascript">
    var $ = jQuery.noConflict();
    $(window).load(function () {
        "use strict";
        var $titlefront = $('.title_front').hide();
        var $titleunder = $('.title_under').hide();
        var $bestman = $('.bestman span').hide();
        var $footernames = $('.footer_names').hide();

        $titlefront.show().arctext({radius: 250});
        $titleunder.show().arctext({radius: 180, dir: -1});
        $bestman.show().arctext({radius: 80});
        $footernames.show().arctext({radius: 120, dir: -1});

        <% if I18n.locale == :fr %>
        $.countdown.setDefaults($.countdown.regional['fr']);
        <% end %>
        $('#defaultCountdown').countdown({until: new Date(2018, 6 - 1, 9, 15), format: 'y-o-d-h'});

    });
</script>
<script type="text/javascript">
    var main_menu = new main_menu.dd("main_menu");
    main_menu.init("main_menu", "menuhover");
</script>

app/views/pages/registry.html.erb
<div id="main_container">

  <%= render 'layouts/menu' %>

  <div class="blog_header_photo">
    <div class="page_header_trans">
      <div class="page_header_title">

      </div>
    </div>
  </div>


  <div class="page_content">
    <div class="full_width_centered">
      <h2><%= t('registry.name') %></h2>
      <div class="left_full">
        <p><%= t('registry.p1') %></p>
        <p><%= t('registry.p2') %></p>
        <p class="form_content"><a href="https://www.myregistry.com/wedding-registry/Sophie-Zhu-and-Gabriel-Gagnon-Montreal-QUEBEC/1529219" class="view_all"><%= t('registy.link') %></a></p>
      </div>

      <div class="clear"></div>
    </div>  <!--end of full width-->
  </div> <!--end of about content-->

  <%= render 'layouts/footer' %>

</div>
<script type="text/javascript">
    var main_menu = new main_menu.dd("main_menu");
    main_menu.init("main_menu", "menuhover");
</script>